### ISSUE TITLE
Unable to use git in AWS MWAA

### ISSUE THREAD

**Issue by boriside** [aws/aws-mwaa-local-runner#174]
Hello,

If we run DBT on AWS MWAA using the following post https://docs.aws.amazon.com/mwaa/latest/userguide/samples-dbt.html unfortunately it is not possible to use packages like so:

packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git" # git URL
    revision: 0.1.21 # tag or branch name

This is an essential part of DBT. Is there any resolution to that or am I overlooking something?

**Comment by cal-lan** [comment]
Is git installed in the container? What is the error you receive?

If the package exists on dbt hub (of which dbt-utils is one) you can refence it like if git is the issue:
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.2
```

You can manually include a custom package (via a manual git clone) and reference it from a local path as a work around. Especially if you are after a specific version, you only need to include it once, but can reference it in many projects.

I have only used git to reference dbt packages when we were maintaining our own custom packages. I'm still interested to see the error you receive because you are right, it is a very useful feature of dbt.

**Comment by mayushko26** [comment]
Closing stale thread
