### ISSUE TITLE
issue with “apache-airflow-providers-mysql” on 2.4.3 (both MWAA and the local runner)

### ISSUE THREAD

**Issue by asafsneh** [aws/aws-mwaa-local-runner#196]
I added apache-airflow-providers-mysql to the requirements (both on the local Docker env, and on MWAA) , but I am getting this error -

```
sh-4.2$ pip3 install apache-airflow-providers-mysql==3.2.1
Defaulting to user installation because normal site-packages is not writeable
Collecting apache-airflow-providers-mysql==3.2.1
  Using cached apache_airflow_providers_mysql-3.2.1-py3-none-any.whl (26 kB)
Collecting mysqlclient>=1.3.6
  Using cached mysqlclient-2.1.1.tar.gz (88 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: mysql_config: command not found
      /bin/sh: mariadb_config: command not found
      /bin/sh: mysql_config: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i9gtkhej/mysqlclient_d737497dbb964ce0837b13587d815526/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-i9gtkhej/mysqlclient_d737497dbb964ce0837b13587d815526/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-i9gtkhej/mysqlclient_d737497dbb964ce0837b13587d815526/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I don’t know how such a basic package of running MySQL commands from Airflow is not working.. didn’t you check it before launching the new version of MWAA.

thanks.

**Comment by navedgaras** [comment]
I am also experiencing issues with MySQL Airflow provider, even though I am not getting an error during package installation, prerequisites that should've been installed with `apache-airflow-providers-mysql `(`MySQLdb`) are missing.

**Comment by melouaer** [comment]
I am also experiencing the same issue..

**Comment by haridqlabs** [comment]
I am getting the same error. We really want to move forward with 2.4 features but unable to continue due to this error.

**Comment by maxanth112** [comment]
I am also getting this error and would love a resolution.

**Comment by lucya-koroleva** [comment]
+1

**Comment by RodionG** [comment]
+1

**Comment by ghost** [comment]
I ran into this issue as well, but needed a fix, so I logged the output and did some digging.

It turns out that the appropriate pre-requisites are installed in `docker/script/systemlibs.sh`, but it is then uninstalled in `docker/script/bootstrap.sh`:
https://github.com/aws/aws-mwaa-local-runner/blob/v2.4.3/docker/script/bootstrap.sh#L13
Specifically the line linked, where it erases `openssl-devel` takes `mariadb-devel` with it.

It turns out that `mariadb-devel` requires 1.0.x of `openssl-devel`, but `openssl11` is the 1.1.x version, so there are problems because they want to occupy the same slots.

If you use the 10.10 version of MariaDB (per official installation instructions), it doesn't have the dependency on `openssl`; remove the existing `mariadb-devel` from `systemlibs.sh` and add the following:
```
curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup -o setup-mariadb
bash ./setup-mariadb --os-type centos --os-version 7
yum install -y --enablerepo mariadb-main MariaDB-devel
rm setup-mariadb
```
I have confirmed this to work.

EDIT:
The problem is that apparently the official AWS MWAA build process has the same bug, so installation winds up failing there also, and the above workaround can't be applied.

I eventually settled on the following workaround:
* Install PyMySQL (any pure-python client for MySQL/MariaDB should work here)
* Set up a Connection of type "generic" with the details. The "extras" part can be used for URL parameters, e.g. `mysql+pymysql://user:password@host:port/schema?charset=utf8mb4` had the extras set as `{"charset": "utf8mb4"}`.
* Use `BaseHook` to retrieve the connection (and massage the URI as needed for SQLAlchemy or etc.); see sample code below
* Connect to the DB as you otherwise would.

This is untested with `airflow-providers-common-sql`.

``` python
from airflow.hooks.base import BaseHook

def uri_from(conn_id: str, protocol: str = "mysql+pymysql") -> str:
    conn = BaseHook.get_connection(conn_id=conn_id)
    uri = conn.get_uri()
    uri = uri.replace("generic", protocol)
    return uri
```

**Comment by seiyeah78** [comment]
According to the AWS side, they have deployed the fixes to enable the use of apache-airflow-providers-mysql in airflow version 2.4.3 in all regions.

**Comment by asafsneh** [comment]
@seiyeah78 how do you know? I see that the last commit on this repo is from 2 weeks ago.. it doesn't seem like there was a change that relates to this issue

**Comment by seiyeah78** [comment]
I contacted the AWS side directly.
Perhaps it is not officially published.
Apparently, it will take about a week to complete the rollout for all regions.
So it may take a little longer.

**Comment by john-jac** [comment]
Updated with https://github.com/aws/aws-mwaa-local-runner/pull/208
