### ISSUE TITLE
Unable to build Docker image due to failed dependencies

### ISSUE THREAD

**Issue by willdecesare** [aws/aws-mwaa-local-runner#214]
All pre-reqs passed. 

Machine: MacBook Pro M1 2020, Ventura 13.2

Command: `./mwaa-local-env build-image`
 
Partial output: 

```
#12 71.12 warning: /mariadb_rpm/MariaDB-common-10.8.6-1.el7.centos.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 1bb943db: NOKEY
#12 71.13 error: Failed dependencies:
#12 71.13 	libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libdl.so.2(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libm.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libpthread.so.0(GLIBC_2.3.2)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	librt.so.1(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.3)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libdl.so.2(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libm.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#12 71.13 	libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
------
executor failed running [/bin/sh -c chmod u+x /bootstrap.sh && /bootstrap.sh]: exit code: 4
```

**Comment by linczakjw** [comment]
Yup, we're getting the same here too on this now-closed issue: https://github.com/aws/aws-mwaa-local-runner/issues/211

**Comment by Taragolis** [comment]
Crosspost from https://apache-airflow.slack.com/archives/CCRR5EBA7/p1676467211394189 (`#airflow-aws` channel from [Community Airflow Slack](https://s.apache.org/airflow-slack))

---

Just FYI, related more official Airflow docker images and official support of ARM, but it could also be a reason why this happen in MWAA images.

Airflow on ARM it is [experimental feature](https://airflow.apache.org/docs/apache-airflow/stable/release-process.html#experimental-features) in OSS implementation. 
AFAIK, community MySQL provider it is maybe the latest community provider which do not have support on ARM yet, [see requirements of package](https://airflow.apache.org/docs/apache-airflow-providers-mysql/4.0.1/index.html#requirements)

The main reason is simple - Oracle doesn’t provide mysql client libraries on Debian for ARM which use **in the official** Airflow images, and we can’t even tests it on ARM.

There is also exists PoC for add this support (experimental) on ARM into the official Airflow: see https://github.com/apache/airflow/pull/29519

---

Due to the fact that Airflow community cannot and does not want to influence Oracle of their support of specific Linux distro and arch. **My personal** recommendations:
1. Use Docker / KubernetesPodOperator and other external operators for interact with MySQL
2. On Mac you could try to run images with linux/amd64 emulation

**Comment by avi-ko** [comment]
+1

**Comment by edgarasnavickas** [comment]
I can confirm that the suggestion from @Taragolis works! Was able to build the docker container with the `--platform linux/amd64` flag specified. Also created a PR for the maintainers to look into: https://github.com/aws/aws-mwaa-local-runner/pull/217
