### ISSUE TITLE
`airflow connections list` returns cryptography.fernet.InvalidToken

### ISSUE THREAD

**Issue by ashley-mallia** [aws/aws-mwaa-local-runner#24]
Running `airflow connections list` on the docker_local-runner container is returning `cryptography.fernet.InvalidToken`

```
sh-4.2$ docker exec -it docker_local-runner_1 /bin/sh
sh-4.2$ source /entrypoint.sh
sh-4.2$ airflow connections list
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/connection_command.py", line 81, in connections_list
    mapper=_connection_mapper,
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/simple_table.py", line 101, in print_as
    dict_data: List[Dict] = [mapper(d) for d in data]
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/simple_table.py", line 101, in <listcomp>
    dict_data: List[Dict] = [mapper(d) for d in data]
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/connection_command.py", line 50, in _connection_mapper
    'extra_dejson': conn.extra_dejson,
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 333, in extra_dejson
    if self.extra:
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 365, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 240, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/usr/local/lib64/python3.7/site-packages/cryptography/fernet.py", line 194, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

I have specified my `FERNET_KEY` in my docker-compose file and run `source /entrypoint.sh` to ensure AIRFLOW__CORE__FERNET_KEY is set

```
local-runner:
    environment:
        - FERNET_KEY=...
```

Other airflow commands work, so it appears to be an issue specifically with accessing connections

```
sh-4.2$ airflow variables list
key    
=======
from ui
```

Any tips for how to remedy this would be appreciated.
Thanks

**Comment by pholterman** [comment]
same problem here, I can add a connection by going to http://localhost:8080/connection/add and the connection works. But when I restart the environment, the connection doesn't work anymore and I get the same error when I execute my DAG.

**Comment by DaniDasBoot** [comment]
Possibly related to #27

**Comment by ashley-mallia** [comment]
Possibly related to #29

**Comment by ashley-mallia** [comment]
I have found a procedure that fixes this, but am not sure why it works.

1. define `fernet_key =  ...` in airflow.cfg
2. run `./mwaa-local-env build-image`
3. run `./mwaa-local-env start`
4. `http://localhost:8080/home` will run successfully 
5. connect to local_runner container `docker exec -it docker_local-runner_1 /bin/sh`
6. `airflow connections list` will return the same error listed above `cryptography.fernet.InvalidToken`

7. run `airflow db reset -y`
8. `airflow connections list` will now work - and it will continue to work even when the container is stopped and restarted.

So it seems that `airflow db reset` needs to be run the first time the db is setup for `airflow connections list` to work.
Can anyone explain why this is the case.

**Comment by dkozlovskyi** [comment]
As a workaround:
1. delete `db-data` local folder
2. run `./mwaa-local-env build-image`
3. run `./mwaa-local-env start`

**Comment by ashley-mallia** [comment]
> As a workaround:
> 
> 1. delete `db-data` local folder
> 2. run `./mwaa-local-env build-image`
> 3. run `./mwaa-local-env start`

For me, this still results in the same problem. The airflow cli still fails to display `airflow connections list`

**Comment by manypozo** [comment]
I would suggest that for local development the `FERNET_KEY` variable remains static and fixed in the docker-compose definition.

First, generate a cryptography key (fernet_key)
```
python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
```

then, copy-paste the printed result into the environment definition of your docker-compose.
```
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=xxx
```

It is better to restart the environment for these changes to take place properly.
- `docker-compose -f ./docker/docker-compose-local.yml down`
- `rm -r db-data`
- `./mwaa-local-env start`

if necessary, replace it in the airflow.cfg as well.

This should solve part of the issue.
The other part is the ability of aws-mwaa-local-runner to perform inner `airflow cli` commands.

This is possible to verify by simply going into the container and execute `airflow version`:
```
docker exec CONTAINER_ID airflow version
```                     
(to check your container_id do: `docker ps`)

The output should be something like:
```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 34, in <module>
    from airflow import settings
  File "/usr/local/lib/python3.7/site-packages/airflow/settings.py", line 37, in <module>
    from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 1098, in <module>
    conf = initialize_config()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 860, in initialize_config
    conf.validate()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 199, in validate
    self._validate_config_dependencies()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 240, in _validate_config_dependencies
    f"error: sqlite C library version too old (< {min_sqlite_version}). "
airflow.exceptions.AirflowConfigException: error: sqlite C library version too old (< 3.15.0). See https://airflow.apache.org/docs/apache-airflow/2.0.2/howto/set-up-database.rst#setting-up-a-sqlite-database
```

In fact, this simply means that CLI is trying to access to the default database (sqlite). We have to override this configuration in order to perform any CLI operations.

Simply add SqlAlchemy connection (`AIRFLOW__CORE__SQL_ALCHEMY_CONN`) to the environment in the docker-compose definition:
```
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=xxx
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
```

Other solution would be to add it in the airflow.cfg file by replacing this line: 
`#sql_alchemy_conn = sqlite:///{AIRFLOW_HOME}/airflow.db` 
by 
`sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres:5432/airflow`


Now, it should be possible to perform `airflow connectios list`.
Possibly helps with  #27 

This solution I propose should be only temporary waiting for the complete integration into the local-runner process.
